#pragma once

#define IDC_MYICON_MDI                      2
#define IDC_MYICON_OL                       3
#define ID_FILE_PRINT_PWC                   4
#define ID_FILE_PRINT_PREVIEW_PWC           5
#define IDC_MYICON_PWC                      6

//SYMED
#define IDD_WINCLASS_DIALOG_MDI             102
#define IDD_ABOUTBOX_MDI                    103
#define IDS_APP_TITLE_MDI                   104
#define IDM_ABOUT_MDI                       105
#define IDM_EXIT_MDI                        106
#define IDS_HELLO_MDI                       107
#define IDI_WINCLASS_MDI                    108
#define IDI_SMALL_MDI                       109
#define IDC_WINCLASS_MDI                    110
#define IDR_MAINFRAME_MDI                   111
#define IDR_TOOLBAR_MDI                     112
#define IDR_MENUHELLO_MDI                   113
#define IDR_TOOLBAR1_MDI                    114
#define IDI_ICONDOC_MDI                     115
#define IDR_SYSTEMBAR_MDI                   116
#define IDr_BITMAP1_MDI                     117
#define IDB_TOOLBAR_MDI                     118
#define IDR_RS1_MDI                         119
#define IDD_OUTOOLKDEMO_DIALOG_OL           120
#define IDD_ABOUTBOX_OL                     121
#define IDS_APP_TITLE_OL                    122
#define IDM_ABOUT_OL                        123
#define IDM_EXIT_OL                         124
#define IDS_HELLO_OL                        125
#define IDI_OUTOOLKDEMO_OL                  126
#define IDI_SMALL_OL                        127
#define IDC_OUTOOLKDEMO_OL                  128
#define IDB_GUI_DOCKBAR_OL                  129
#define IDR_MAINFRAME_OL                    130
#define IDB_BITMAP1_OL                      131
#define IDR_TOOLBAR_OL                      132
#define IDB_Toolbox_OL                      133
#define IDB_TOOLBOX_OL                      134
#define IDB_DB_OL                           135
#define IDB_TREE_OL                         136
#define IDB_TOOLBAR_OL                      137
#define IDD_WINCLASS_DIALOG_PWC             138
#define IDD_ABOUTBOX_PWC                    139
#define IDM_ABOUT_PWC                       140
#define IDM_EXIT_PWC                        141
#define IDI_WINCLASS_PWC                    142
#define IDI_SMALL_PWC                       143
#define IDC_WINCLASS_PWC                    144
#define IDC_BASEMENU_PWC                    145
#define IDB_GUI_DOCKBAR_PWC                 146
#define IDR_MAINFRAME_PWC                   147
#define IDR_TOOLBAR_PWC                     148
#define IDR_MAINTOOLBAR_PWC                 149
#define IDR_STANDAR_PWC                     150
#define IDR_MENUHELLO_PWC                   151
#define IDB_Toolbox_PWC                     152
#define IDB_TOOLBOX_PWC                     153
#define IDR_TOOLBAR1_PWC                    154
#define IDR_EDITTOOLBAR_PWC                 155
#define IDI_ICONDOC_PWC                     156
#define IDR_SYSTEMBAR_PWC                   157
#define IDR_BUILD_PWC                       158
#define IDB_MAINTOOLBAR_PWC                 159
#define IDB_EDITTOOLBAR_PWC                 160
#define IDB_BUILD_PWC                       161
#define ID_Menu_PWC                         162
#define ID_Menu157_PWC                      163
#define IDR_MENU1_PWC                       164
#define IDI_ICON1_PWC                       165
#define IDB_STANDAR_PWC                     166
#define IDB_TREEEXPLORER_PWC                167
#define IDB_DB_PWC                          168
#define IDB_OUTLOOK_PWC                     169
#define IDR_MENUOPTION_PWC                  170

#define ID_TOOLBAR_MDI                      551
#define ID_TOOLBAR_PWC                      552

//control
#define IDC_COMBONOMBRE_MDI                 1000
#define IDC_GROUPBOX_MDI                    1001
#define IDC_EDITAR_MDI                      1002
#define IDC_LISTA_MDI                       1003
#define IDC_EDIT_MDI                        1004
#define IDC_COMBONOMBRE_PWC                 1005
#define IDC_GROUPBOX_PWC                    1006
#define IDC_EDITAR_PWC                      1007
#define IDC_LISTA_PWC                       1008
#define IDC_EDIT_PWC                        1009

//command
#define ID_MENU_NEW_MDI                     32771
#define ID_FILE_NEW_MDI                     32772
#define ID_FILE_OPEN_MDI                    32773
#define ID_FILE_SAVE_MDI                    32774
#define ID_EDIT_CUT_MDI                     32775
#define ID_STATUSBAR_MDI                    32776
#define ID_FILE_CLOSE_MDI                   32777
#define ID_WINDOW_NEW_MDI                   32778
#define ID_WINDOW_CASCADE_MDI               32779
#define ID_WINDOW_TILE_HORZ_MDI             32780
#define ID_WINDOW_ARRANGE_MDI               32781
#define ID_BOTONNEGRO_MDI                   32782
#define ID_BOTONROJO_MDI                    32783
#define ID_BUTTON32785_MDI                  32784
#define ID_BUTTON32786_MDI                  32785
#define ID_BUTTON32787_MDI                  32786
#define ID_BUTTON32788_MDI                  32787
#define ID_BUTTON32789_MDI                  32788
#define ID_BUTTON32790_MDI                  32789
#define IDM_OPEN1_MDI                       32790
#define IDM_OPEN2_MDI                       32791
#define ID_FILE_NEW_OL                      32792
#define ID_FILE_OPEN_OL                     32793
#define ID_FILE_PRINTER                     32794
#define ID_FILE_SAVE_OL                     32795
#define ID_FIND_OL                          32796
#define ID_APP_ABOUT_OL                     32797
#define ID_NEW_MAIL_OL                      32798
#define ID_NEW_FAX_OL                       32799
#define ID_NEW_POST_FOLDER                  32800
#define ID_NEW_FOLDER_OL                    32801
#define ID_NEW_SHORTCUT_OL                  32802
#define ID_NEW_APPOINMENT_OL                32803
#define ID_NEW_MEETING_OL                   32804
#define ID_NEW_CONTRACT_OL                  32805
#define ID_NEW_DISTRIBUTION_LIST_OL         32806
#define ID_NEW_TASK_OL                      32807
#define ID_NEW_TASK_REQUEST_OL              32808
#define ID_NEW_JOURNAL_ENTRY_OL             32809
#define ID_NEW_NOTE_OL                      32810
#define ID_MAIL_SEND_OL                     32811
#define ID_MAIL_SAVE_OL                     32812
#define ID_FILE_SAVE_AS_OL                  32813
#define ID_MAIL_SAVE_ATTACHMENTS_OL         32814
#define ID_MAIL_SAVE_STATIONERY_OL          32815
#define ID_MAIL_DELETE_OL                   32816
#define ID_MAIL_MOVE_TO_FOLDER_OL           32817
#define ID_MAIL_COPY_TO_FOLDER_OL           32818
#define ID_FILE_PRINT_PREVIEW_OL            32819
#define ID_FILE_PRINT_OL                    32820
#define ID_MAIL_PROPERTIES_OL               32821
#define ID_MAIL_CLOSE_OL                    32822
#define ID_EDIT_UNDO_OL                     32823
#define ID_EDIT_REDO_OL                     32824
#define ID_EDIT_CUT_OL                      32825
#define ID_EDIT_COPY_OL                     32826
#define ID_COMBOBOX_OL                      32827
#define ID_EDIT_PASTE_OL                    32828
#define ID_MAIL_SPELL_OL                    32829
#define ID_MAIL_CHECK_NAMES_OL              32830
#define ID_ADDRESS_BOOK_OL                  32831
#define ID_TOOLS_ENTRY_OL                   32832
#define ID_VIEW_CUSTOMIZE_OL                32833
#define ID_ADDRESBOOK_OL                    32834
#define ID_FILE_NEW_PWC                     32835
#define ID_FILE_OPEN_PWC                    32836
#define ID_FILE_SAVE_PWC                    32837
#define ID_EDIT_CUT_PWC                     32838
#define ID_STATUSBAR_PWC                    32839
#define ID_VIEW_TOOLBARS_PWC                32840
#define ID_BOTONNEGRO_PWC                   32841
#define ID_BOTONROJO_PWC                    32842
#define ID_BUTTON32785_PWC                  32843
#define ID_BUTTON32786_PWC                  32844
#define ID_BUTTON32787_PWC                  32845
#define ID_DUMMY_COMPILE_PWC                32846
#define ID_BUTTON32788_PWC                  32847
#define ID_DUMMY_BUILD_PWC                  32848
#define ID_BUTTON32789_PWC                  32849
#define ID_BUTTON32790_PWC                  32850
#define ID_DUMMY_EXECUTE_PWC                32851
#define IDM_OPEN1_PWC                       32852
#define ID_DUMMY_GO_PWC                     32853
#define IDM_OPEN2_PWC                       32854
#define ID_DUMMY_SELECT_ACTIVE_CONFIGURATION_PWC 32855
#define ID_COMBOBOX_PWC                     32856
#define ID_DUMMY_REBUILD_ALL_PWC            32857
#define ID_DUMMY_CLEAN_PWC                  32858
#define ID_BUTTON32799_PWC                  32859
#define ID_BUTTON32800_PWC                  32860
#define ID_BUTTON32802_PWC                  32861
#define ID_BUTTON32803_PWC                  32862
#define ID_BUTTON32804_PWC                  32863
#define ID_NAVIGATE_PWC                     32864
#define ID_BUTTON32805_PWC                  32865
#define ID_cUT1_PWC                         32866
#define ID_OPTION2_PWC                      32867
#define ID_FILE_CLOSE_PWC                   32868
#define ID_FILE_SAVE_AS_PWC                 32869
#define ID_PRINT_PWC                        32870
#define ID_VIEW_MAINTOOLBAR_PWC             32871
#define ID_VIEWCOMPILEBAR_PWC               32872
#define ID_VIEWSTATUSBAR_PWC                32873
#define ID_Menu32814_PWC                    32874
#define ID_VIEWRESOURCEVIEW_PWC             32875
#define ID_TOOLS_MACRO_PWC                  32876
#define ID_VIEWHELPWINDOW_PWC               32877
#define ID_VIEWTOOLBOX_PWC                  32878
#define ID_VIEWCLASSVIEW_PWC                32879
#define ID_TOOLS_ENTRY_PWC                  32880
#define ID_VIEW_OUTLOOKWINDOW_PWC           32881
#define ID_VIEW_SOLUTIONEXPLORER_PWC        32882
#define ID_VIEW_WORTABDEMO_PWC              32883
#define ID_VIEWSHELPWINDOW_PWC              32884
#define ID_SAVE_ALL_PWC                     32885
#define ID_BUILPROJECT_PWC                  32886
#define ID_HELP_KEYBOARDMAP_PWC             32887
#define ID_TOOLS_OPTIONS_PWC                32888
#define ID_VIEW_APP_LOOK_PWC                32889

#define ID_FILE_PRINT_SETUP_PWC             57609
#define ID_FILE_MRU_FILE1_PWC               57610
#define ID_EDIT_COPY_PWC                    57611
#define ID_EDIT_FIND_PWC                    57612
#define ID_EDIT_PASTE_PWC                   57613
#define ID_EDIT_UNDO_PWC                    57614
#define ID_EDIT_REDO_PWC                    57615
#define ID_APP_ABOUT_PWC                    57616
#define ID_APP_EXIT_PWC                     57617
#define ID_VIEW_STATUS_BAR_PWC              57618
#define ID_CANCEL_PWC                       57619
#define ID_COMPILE_PWC                      57620

#define IDC_STATIC                      -1
