#pragma once

#define IDC_MYICON_MDI                      2
#define IDD_WINCLASS_DIALOG_MDI             102
#define IDD_ABOUTBOX_MDI                    103
#define IDS_APP_TITLE_MDI                   103
#define IDM_ABOUT_MDI                       104
#define IDM_EXIT_MDI                        105
#define IDS_HELLO_MDI                       106
#define IDI_WINCLASS_MDI                    107
#define IDI_SMALL_MDI                       108
#define IDC_WINCLASS_MDI                    109
#define IDR_MAINFRAME_MDI                   128
#define IDR_TOOLBAR_MDI                     129
#define IDR_MENUHELLO_MDI                   132
#define IDR_TOOLBAR1_MDI                    134
#define IDI_ICONDOC_MDI                     139
#define IDR_SYSTEMBAR_MDI                   140
#define IDr_BITMAP1_MDI                     146
#define IDB_TOOLBAR_MDI                     150
#define IDR_RS1_MDI                         152
#define ID_TOOLBAR_MDI                      551
#define IDC_COMBONOMBRE_MDI                 1000
#define IDC_GROUPBOX_MDI                    1001
#define IDC_EDITAR_MDI                      1002
#define IDC_LISTA_MDI                       1004
#define IDC_EDIT_MDI                        1006
#define ID_MENU_NEW_MDI                     32771
#define ID_FILE_NEW_MDI                     32773
#define ID_FILE_OPEN_MDI                    32774
#define ID_FILE_SAVE_MDI                    32775
#define ID_EDIT_CUT_MDI                     32776
#define ID_STATUSBAR_MDI                    32777
#define ID_FILE_CLOSE_MDI                   32778
#define ID_WINDOW_NEW_MDI                   32779
#define ID_WINDOW_CASCADE_MDI               32780
#define ID_WINDOW_TILE_HORZ_MDI             32781
#define ID_WINDOW_ARRANGE_MDI               32782
#define ID_BOTONNEGRO_MDI                   32783
#define ID_BOTONROJO_MDI                    32784
#define ID_BUTTON32785_MDI                  32785
#define ID_BUTTON32786_MDI                  32786
#define ID_BUTTON32787_MDI                  32787
#define ID_BUTTON32788_MDI                  32788
#define ID_BUTTON32789_MDI                  32789
#define ID_BUTTON32790_MDI                  32790
#define IDM_OPEN1_MDI                       32791
#define IDM_OPEN2_MDI                       32792
#define IDC_STATIC                      -1
