//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by WinClass.rc
//
#define ID_FILE_PRINT_PWC                   0
#define ID_FILE_PRINT_PREVIEW_PWC           0
#define IDC_MYICON_PWC                      2
#define IDD_WINCLASS_DIALOG_PWC             102
#define IDD_ABOUTBOX_PWC                    103
#define IDM_ABOUT_PWC                       104
#define IDM_EXIT_PWC                        105
#define IDI_WINCLASS_PWC                    107
#define IDI_SMALL_PWC                       108
#define IDC_WINCLASS_PWC                    109
#define IDC_BASEMENU                    109
#define IDB_GUI_DOCKBAR_PWC                 110
#define IDR_MAINFRAME_OL                   128
#define IDR_TOOLBAR_PWC                     129
#define IDR_MAINTOOLBAR                 129
#define IDR_STANDAR                     129
#define IDR_MENUHELLO_PWC                   132
#define IDB_Toolbox_PWC                     133
#define IDB_TOOLBOX_PWC                     133
#define IDR_TOOLBAR1_PWC                    134
#define IDR_EDITTOOLBAR                 134
#define IDI_ICONDOC_PWC                     139
#define IDR_SYSTEMBAR_PWC                   140
#define IDR_BUILD                       140
#define IDB_MAINTOOLBAR                 151
#define IDB_EDITTOOLBAR                 153
#define IDB_BUILD                       154
#define ID_Menu                         156
#define ID_Menu157                      157
#define IDR_MENU1                       158
#define IDI_ICON1                       159
#define IDB_STANDAR                     161
#define IDB_TREEEXPLORER                162
#define IDB_DB_PWC                          163
#define IDB_OUTLOOK                     164
#define IDR_MENUOPTION                  165
#define ID_TOOLBAR_PWC                      551
#define IDC_COMBONOMBRE_PWC                 1000
#define IDC_GROUPBOX_PWC                    1001
#define IDC_EDITAR_PWC                      1002
#define IDC_LISTA_PWC                       1004
#define IDC_EDIT_PWC                        1006
#define ID_FILE_NEW_PWC                     32773
#define ID_FILE_OPEN_PWC                    32774
#define ID_FILE_SAVE_PWC                    32775
#define ID_EDIT_CUT_PWC                     32776
#define ID_STATUSBAR_PWC                    32777
#define ID_VIEW_TOOLBARS                32781
#define ID_BOTONNEGRO_PWC                   32783
#define ID_BOTONROJO_PWC                    32784
#define ID_BUTTON32785_PWC                  32785
#define ID_BUTTON32786_PWC                  32786
#define ID_BUTTON32787_PWC                  32787
#define ID_DUMMY_COMPILE                32787
#define ID_BUTTON32788_PWC                  32788
#define ID_DUMMY_BUILD                  32788
#define ID_BUTTON32789_PWC                  32789
#define ID_BUTTON32790_PWC                  32790
#define ID_DUMMY_EXECUTE                32790
#define IDM_OPEN1_PWC                       32791
#define ID_DUMMY_GO                     32791
#define IDM_OPEN2                       32792
#define ID_DUMMY_SELECT_ACTIVE_CONFIGURATION 32794
#define ID_COMBOBOX_PWC                     32797
#define ID_DUMMY_REBUILD_ALL            32798
#define ID_DUMMY_CLEAN                  32799
#define ID_BUTTON32799                  32799
#define ID_BUTTON32800                  32800
#define ID_BUTTON32802                  32802
#define ID_BUTTON32803                  32803
#define ID_BUTTON32804                  32804
#define ID_NAVIGATE                     32804
#define ID_BUTTON32805                  32805
#define ID_cUT1                         32806
#define ID_OPTION2                      32807
#define ID_FILE_CLOSE_PWC                   32808
#define ID_FILE_SAVE_AS_PWC                 32809
#define ID_PRINT                        32810
#define ID_VIEW_MAINTOOLBAR             32811
#define ID_VIEWCOMPILEBAR               32812
#define ID_VIEWSTATUSBAR                32813
#define ID_Menu32814                    32814
#define ID_VIEWRESOURCEVIEW             32815
#define ID_TOOLS_MACRO                  32816
#define ID_VIEWHELPWINDOW               32816
#define ID_VIEWTOOLBOX                  32817
#define ID_VIEWCLASSVIEW                32818
#define ID_TOOLS_ENTRY_PWC                  32819
#define ID_VIEW_OUTLOOKWINDOW           32819
#define ID_VIEW_SOLUTIONEXPLORER        32820
#define ID_VIEW_WORTABDEMO              32821
#define ID_VIEWSHELPWINDOW              32822
#define ID_SAVE_ALL                     32823
#define ID_BUILPROJECT                  32824
#define ID_HELP_KEYBOARDMAP             32845
#define ID_TOOLS_OPTIONS                32856
#define ID_VIEW_APP_LOOK                32950
#define ID_FILE_PRINT_SETUP             57609
#define ID_FILE_MRU_FILE1               57616
#define ID_EDIT_COPY_PWC                    57634
#define ID_EDIT_FIND                    57636
#define ID_EDIT_PASTE_PWC                   57637
#define ID_EDIT_UNDO_PWC                    57643
#define ID_EDIT_REDO_PWC                    57644
#define ID_APP_ABOUT_PWC                    57664
#define ID_APP_EXIT                     57665
#define ID_VIEW_STATUS_BAR              59393
#define ID_CANCEL                       61536
#define ID_COMPILE                      61728
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        168
#define _APS_NEXT_COMMAND_VALUE         32825
#define _APS_NEXT_CONTROL_VALUE         1008
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
